# Generated by Django 3.2.5 on 2021-10-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211029_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooking',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='userbooking',
            name='guests',
        ),
    ]
