# Generated by Django 3.2.5 on 2021-11-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211101_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='house_name',
            field=models.CharField(default='Tremont', max_length=100),
            preserve_default=False,
        ),
    ]
