# Generated by Django 3.2.5 on 2021-11-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='thumbnail',
            field=models.ImageField(default='frontend_django/static/images/default.png', upload_to='frontend_django/static/images'),
        ),
    ]
